In [1]:
#Day 1
import torch as t


In [2]:
#Tensors
#Creating tensor of rank 2 random values by using torch.rand()
x=t.tensor([[0,0,1],[1,1,1],[0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [3]:
#Zeros and ones
t.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [4]:
#Can perform methematical operaitons with tensors
t.ones(1,2) + t.ones(1,2)

tensor([[2., 2.]])

In [5]:
# Pulling value using item()
t.rand(1).item()

0.6895507574081421

In [6]:
#Tensors can live in the CPU or on the GPU and can be copies between devices by the to() function()
cpu_tensor = t.rand(2)
cpu_tensor.device

device(type='cpu')

In [7]:
gpu_tensor = cpu_tensor.to('cuda')
gpu_tensor.device

device(type='cuda', index=0)

In [12]:
#Day 2
#Tensor Operations
t.rand(2,2).max()

tensor(0.9295)

In [13]:
t.rand(2,2).max().item()

0.998210072517395

In [14]:
long_tensor = t.tensor([[0,0,1],[1,1,1],[0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [16]:
float_tensor = t.tensor([[0,0,1],[1,1,1],[0,0,0]]).to(dtype=t.float32)
float_tensor.type()

'torch.FloatTensor'

In [19]:
#Reshaping from 784 to 1*28*28
flat_tensor = t.rand(784)
new_tensor = flat_tensor.reshape(1,28,28)
new_tensor.shape

torch.Size([1, 28, 28])

In [24]:
#chaging indexes
hwc_tensor = t.rand(640,480,3)
chw_tensor = hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])

In [2]:
from torchvision import transforms

In [3]:
train_data_path = "./Fish-vs-Cats/train"

In [4]:
transforms = transforms.Compose([transforms.Resize(64),transforms.ToTensor(),transforms.Normalize(mean=[0.485,0.456,0.406],std=[0.229,0.224,0.225])])

In [8]:
import torchvision as t
train_data = t.datasets.ImageFolder(root=train_data_path,transform=transforms)

In [9]:
val_data_path = "./Fish-vs-Cats/val"
val_data = t.datasets.ImageFolder(root=val_data_path,transform=transforms)

In [10]:
test_data_path = "./Fish-vs-Cats/val"
test_data = t.datasets.ImageFolder(root=test_data_path,transform=transforms)

In [14]:
from torch.utils import data
batch_size = 64
train_data_loader = data.DataLoader(train_data, batch_size=batch_size)
val_data_loader = data.DataLoader(val_data, batch_size=batch_size)
test_data_loader = data.DataLoader(test_data,batch_size=batch_size)